apiVersion: apps/v1
kind: Deployment
metadata:
  name: shiftzilla-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shiftzilla-server
  template:
    metadata:
      labels:
        app: shiftzilla-server
    spec:
      containers:
      - name: server
        image: docker-registry.default.svc:5000/shiftzilla/shiftzilla
        args:
          - /usr/bin/ruby
          - -run
          - -e
          - httpd
          - /shiftzilla/storage/www
        volumeMounts:
        - name: shiftzilla-files
          mountPath: /shiftzilla/storage
      volumes:
      - name: shiftzilla-files
        persistentVolumeClaim:
          claimName: shiftzilla-state

